import esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import { builtinModules } from 'node:module';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtinModules],
	format: 'cjs',
	target: 'es2016',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	// Lists every input bundled into main.js; scripts/check-bundled-deps.mjs reads it.
	metafile: true,
});

if (prod) {
	const result = await context.rebuild();
	writeFileSync('meta.json', JSON.stringify(result.metafile));
	process.exit(0);
} else {
	await context.watch();
}
